Implement News Headlines
MLH-Fellowship/prep-project-23.MAR.PREP.1 pull request #25
Opened 2023-03-17 04:53 UTC by pradumna-gautam

Solve Issue #24

2023-03-17 16:57 UTC, pradumna-gautam commented on src/App.js
> +        <div>
@swimmingHaribo I think we can add a button to show the news, instead of always showing it, as UI is not looking good like that.

2023-03-17 20:23 UTC, Garvit1809 commented on src/News/News.js
1) Add an error handler (a try catch block) in case there are any issues with API request in the fetchNews function
2) Also, we should add a clean-up function in the useEffect hook, as user may click the button multiple times, so the clean up func would make the application faster

2023-03-18 04:57 UTC, Garvit1809 commented
Now looks good, Good job !!

2023-03-20 16:47 UTC, sumana2001 reviewed
<img width="1440" alt="Screenshot 2023-03-20 at 10 16 41 PM" src="https://user-images.githubusercontent.com/63084088/226410330-feb88c3d-c0f3-417f-92d0-ac32a52e14cc.png">
Seems like the api you have used doesn't works only on localhost, could you look for some other free news API that does work?

2023-03-23 17:36 UTC, Garvit1809 commented
1_The branch has conflicts

2023-03-24 03:46 UTC, sumana2001 requested changes
![Screenshot_2023-03-24-09-15-10-02_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/63084088/227419307-b27a5a4b-355e-4296-b3d4-6a5626c4659f.jpg)
![Screenshot_2023-03-24-09-15-02-09_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/63084088/227419326-c71cf7df-e95e-4854-8d22-cc245a9e9de8.jpg)
It doesn't seem to be mobile responsive

2023-03-24 05:23 UTC, merged