feat: add air quality index
MLH-Fellowship/prep-project-23.MAR.PREP.1 pull request #44
Opened 2023-03-23 14:22 UTC by Keshraf

- Added a indicator showing air quality

Closes #43

2023-03-23 18:01 UTC, mukhsadr approved these changes
LGTM!

2023-03-23 18:30 UTC, mukhsadr commented on src/components/AQICard/styles.css
> +.aqi-indicator-text {
can you also give background for text so when the background of the app changes, the text is still visible!

![image](https://user-images.githubusercontent.com/105518066/227313011-ee3903a7-4720-40d0-b04a-6004f17364ae.png)

2023-03-23 18:43 UTC, mukhsadr approved these changes
It looks good to me. After my review, I can say that air quality feature works fine. Indicator is changing accordingly to data changes and text is bold and visible in various background. @sumana2001 I think it is good to merge it now.

2023-03-23 19:27 UTC, sumana2001 requested changes
One small addition, could you add a title or a text saying air quality or something so that users know what scale it is showing

2023-03-24 06:14 UTC, sumana2001 reviewed
Since there is no change in package.json, please remove any changes made to yarn.lock and fix merge conflicts and then I think we are good to go

2023-03-24 06:20 UTC, Keshraf commented
> Since there is no change in package.json, please remove any changes made to yarn.lock and fix merge conflicts and then I think we are good to go

I have resolved the merge conflicts and added the heading. The yarn.lock was added to the PR when I initially fixed the merge conflicts.

2023-03-24 06:22 UTC, sumana2001 requested changes
Seems like all the checks are failing. Please check the deploy log and fix the issue

2023-03-24 06:35 UTC, Keshraf commented
> Seems like all the checks are failing. Please check the deploy log and fix the issue

The problem was in the yarn.lock file. Had to ```rm -rf node_modules``` and then reinstall all the packages ```yarn install```

2023-03-24 07:10 UTC, Keshraf commented
@sumana2001 please review and merge this PR. I have solved merge conflicts thrice since the morning 🥲

2023-03-24 07:15 UTC, sumana2001 commented
Oh I am so sorry. This is the last time. let me know when you're done, I'll merge your PR first

2023-03-24 07:17 UTC, Keshraf commented
@sumana2001, you can review it and merge the PR. I am done with it.

2023-03-24 07:17 UTC, sumana2001 commented
I can still see App.js in conflicting

2023-03-24 07:21 UTC, merged

2023-03-24 07:21 UTC, Keshraf commented
@sumana2001 fixed now. I think I have become experienced in solving merge conflicts.

2023-03-24 07:24 UTC, sumana2001 commented
Haha great hob! That's the goal💯